"""
Interactive, resumable annotation tool for the Cantonese -> English gold set.
This is where YOU do the bilingual review the acceptance criteria asks for,
for the one direction with no existing free dataset.

For each candidate sentence it shows you the Cantonese source and the raw MT
English output, and asks you to mark error spans (same schema SiniticMTError
uses: a text segment, an error type, a severity). You can also mark a
sentence as clean (no errors) or skip it.

Progress is saved after every sentence, so you can stop anytime (Ctrl+C or
type 'q') and resume later - it picks up where you left off. Stops
automatically once you've labeled 40 sentences (the target); you can keep
going if you want more, up to the 50 max the task asks for.

Run:
    python3 gold_sets/annotate_yueen.py
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config import GOLD_DIR, GOLD_SET_SIZE, GOLD_SET_MAX
from common import read_jsonl, write_jsonl, human_mqm_score

VALID_SEVERITY = {"minor": "Minor", "major": "Major", "critical": "Critical"}
VALID_TYPE_HINTS = "Mistranslation / Omission / Addition / Grammar / Spelling / Typography / Untranslated / Unintelligible"


def load_progress(path):
    if os.path.exists(path):
        return {g["gold_id"]: g for g in read_jsonl(path)}
    return {}


def annotate_one(cand):
    print("\n" + "=" * 70)
    print(f"Cantonese source:\n  {cand['source_yue']}")
    print(f"\nMT English output ({cand['generated_by_model']}):\n  {cand['mt_en_candidate']}")
    print("-" * 70)
    print("Mark errors in the ENGLISH MT output above.")
    print(f"Error types (free text, e.g. one of: {VALID_TYPE_HINTS})")
    print("Enter one error per line as:  <exact text segment> | <type> | <severity: minor/major/critical>")
    print("Type nothing + Enter when done. Type 'clean' immediately if there are no errors. Type 'q' to quit and save.")

    spans = []
    while True:
        line = input("> ").strip()
        if line == "":
            break
        if line.lower() == "q":
            return None  # signal quit
        if line.lower() == "clean":
            spans = []
            break
        parts = [p.strip() for p in line.split("|")]
        if len(parts) != 3:
            print("  Format must be: text | type | severity  (or 'clean' / blank to finish)")
            continue
        text, etype, sev = parts
        sev_norm = VALID_SEVERITY.get(sev.lower())
        if not sev_norm:
            print("  Severity must be minor, major, or critical")
            continue
        spans.append({"error_text_segment": text, "error_type": etype, "error_severity": sev_norm})
        print(f"  added: [{sev_norm}] {etype} - '{text}'")

    return spans


def main():
    cand_path = os.path.join(GOLD_DIR, "candidates_yue_en.jsonl")
    out_path = os.path.join(GOLD_DIR, "gold_yue_en.jsonl")

    if not os.path.exists(cand_path):
        print("No candidates found. Run gold_sets/prepare_yueen_candidates.py first.")
        return

    candidates = read_jsonl(cand_path)
    done = load_progress(out_path)
    print(f"{len(done)} sentences already annotated. Target: {GOLD_SET_SIZE} (max {GOLD_SET_MAX}).")

    for cand in candidates:
        gold_id = cand["candidate_id"]
        if gold_id in done:
            continue
        if len(done) >= GOLD_SET_MAX:
            print(f"Reached the {GOLD_SET_MAX}-sentence cap.")
            break

        spans = annotate_one(cand)
        if spans is None:
            print("Stopping. Progress saved.")
            break

        entry = {
            "gold_id": gold_id,
            "direction": "yue_to_en",
            "source_text": cand["source_yue"],
            "mt_text": cand["mt_en_candidate"],
            "reference_text": None,
            "human_error_spans": spans,
            "human_score": human_mqm_score(spans),
            "provenance": f"Self-annotated (bilingual review) - MT generated by {cand['generated_by_model']}",
        }
        done[gold_id] = entry
        write_jsonl(out_path, list(done.values()))  # save after every sentence

        if len(done) >= GOLD_SET_SIZE:
            cont = input(f"\nReached target of {GOLD_SET_SIZE}. Keep going? (y/N): ").strip().lower()
            if cont != "y":
                break

    print(f"\nDone. {len(done)} sentences saved to {out_path}")


if __name__ == "__main__":
    main()
